# spring 相关配置
spring:
  application:
    name: memorial
  datasource: # 数据库链接配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmn # => 请检查所使用的数据库
    username: root
    password: 040905 # => 密码请改成自己的
  servlet:
    multipart: # 文件上传限制配置
      max-file-size: 10MB
      max-request-size: 100MB

# mybatis 相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 将日志输出到控制台
    map-underscore-to-camel-case: true # 开启驼峰命名转换，需要类中字段名和表中列明相对应    c_id => cId
  type-aliases-package: org.tsubakice.data.table # 扫描指定包中的类，以避免写全类名 => 请检查所使用的包
  mapper-locations: # 扫描 mapper 文件
    - classpath:org/tsubakice/mapper/*.xml # => 请检查 sql 映射文件所在目录是否与 mapper 接口所在目录一致

# springboot 事务管理日志开关
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

# token 相关配置
token:
  secret: a34cae2353084651811ca39b9e262d68 # 密钥，长度至少 32 位
  issuer: tsubaki # 签发者
  subject: authentication # 主题
  issuedAt: 0 # 从何时开始生效，默认从当前开始生效，计算方式为，当前时间戳 + 该项的值(单位：ms)
  expiration: 604800000 # 有效时长，默认为一周(604800000)，计算方式同 issuedAt 一致

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui # 自定义 swagger 前端请求路径
    tags-sorter: alpha # 按字母排序
    operations-sorter: alpha # or method 按方法定义顺序排序
  api-docs:
    path: /v3/api-docs # 后端请求地址
    enabled: true # 开启文档功能
  group-configs: # 分组配置，可配置多个分组
    - group: default # 分组名称
      paths-to-match: # 配置需要匹配的路径
        - '/**'
      packages-to-scan: # 配置要扫描的包的路径，一般配置到启动类所在的包名
        - org.tsubakice

# knife4j 的增强配置
knife4j:
  enable: true # 开启 knife4j 增强配置
  production: false # 标识是否为生产环境(是否关闭接口文档)
  setting:
    language: zh_cn
    enable-swagger-models: true
    swagger-model-name: 实体列表
    enable-dynamic-parameter: true # 开启动态请求参数
  basic: # 配置 Swagger 的 Basic 认证功能
    enable: false
    username: tsubaki # 用户名自定义
    password: 040905 # 密码自定义
